tu-graz-library/invenio-records-marc21

- invenio_records_marc21/services/components.py
- invenio_records_marc21/services/schemas/access.py
- invenio_records_marc21/services/services.py
- tests/services/schemas/test_access.py
- tests/services/test_create_record.py
Updating access agent schema allow 1-n owned_by of a marc21 record
> Create record with 1-n agents

- invenio_records_marc21/config.py
- invenio_records_marc21/ext.py
- invenio_records_marc21/resources/__init__.py
- invenio_records_marc21/resources/config.py
- invenio_records_marc21/resources/resources.py
- invenio_records_marc21/serializers/ui/__init__.py
- invenio_records_marc21/serializers/ui/schema.py
- invenio_records_marc21/static/templates/invenio_records_marc21/results.html
- invenio_records_marc21/views.py
- setup.py
**Aim**
It should be possible to display marc21 records in invenio.
Create records can be listed with: 
`curl -k https://127.0.0.1:5000/api/marc21?prettyprint=1`
It's also given a possibility to search for a specific type of records:
`curl -k https://127.0.0.1:5000/api/marc21?q=open`
To display a specific record:
`https://127.0.0.1:5000/api/marc21/<pid_value>`
> UI for marc21 records

- MANIFEST.in
- invenio_records_marc21/cli.py
- invenio_records_marc21/services/__init__.py
- invenio_records_marc21/services/record/__init__.py
- invenio_records_marc21/services/record/fields/__init__.py
- invenio_records_marc21/services/record/fields/control.py
- invenio_records_marc21/services/record/fields/data.py
- invenio_records_marc21/services/record/fields/leader.py
- invenio_records_marc21/services/record/fields/sub.py
- invenio_records_marc21/services/record/metadata.py
- invenio_records_marc21/services/record/schema/MARC21slim.xsd
- invenio_records_marc21/services/services.py
- setup.py
- tests/services/conftest.py
- tests/services/record/conftest.py
- tests/services/record/fields/conftest.py
- tests/services/record/fields/test_controlfield.py
- tests/services/record/fields/test_datafield.py
- tests/services/record/fields/test_leaderfield.py
- tests/services/record/fields/test_subfield.py
- tests/services/record/test_marc21_metadata.py
adding Marc21Metadata object allowing other modules to build a marc21 XML and store it in the repository.
Also, add a test set for metadata and for the fields in the metadata structure.
> Marc21 metadata

- invenio_records_marc21/services/record/metadata.py
lxml parseTree adds xml namespace to element tag name eq. '{http://www.loc.gov/MARC21/slim}datafield'
changing search of element tag names to containing datafield or subfield substring.
**Test:**
`invenio marc21 demo -f data/example-record.xml -m True -n 1`
> Bugfix: create metadata with xmlns in records tag

- .github/workflows/tests.yml
Build CI with setuptools version 57.5.0 due to the issue #2769 raised from dependency module fs
> CI: build errors

- invenio_records_marc21/services/config.py
- invenio_records_marc21/templates/invenio_records_marc21/records/export.html
- invenio_records_marc21/ui/records/decorators.py
- invenio_records_marc21/ui/records/records.py
Update the marc21 record file service and print corrected links to files  e.g. 
`https://127.0.0.1:5000/api/marc21/zkqdc-09b59/files` instead of `https://127.0.0.1:5000/api/records/zkqdc-09b59/files`
and passing files to the record landing page.
> Marc21 File service update

- invenio_records_marc21/templates/invenio_records_marc21/record.html
- invenio_records_marc21/templates/invenio_records_marc21/records/export.html
- invenio_records_marc21/ui/records/records.py
adding the pass_is_preview decorator for the export page and
load the versionlist of a record in the sidebar
> Bugfix(ui): record exporter page

- invenio_records_marc21/records/systemfields/providers.py
With that hack it is possible to create a record with a pre-calculated marcid.
This approach is necessary because there exists for now some DOI's with marcid (with no
corresponding record in the repository) where the records should
have then also the same marcid when they will be created then in the repository.
To set the pre-calculated marcid it has to be assigned to
MarcDraftProvider.predefined_pid_value before the creation of the record with
the corresponding service
> add functionality to set a pre-calculated marcid

- setup.py
installing invenio-rdm-records version less than 0.34.0 in order to avoid  features in development
> Dependency update

- invenio_records_marc21/services/record/metadata.py
- tests/services/record/test_marc21_metadata.py
remove deprecated function and adding testset to load marc21metadata lxml trees
> Bugfix: marc21metadata load etree

- docs/conf.py
- language = None in Sphinx 5.0.0 should be set to "en"
- use datetime to set the current year in the documentation
> fix combined fixes

- invenio_records_marc21/records/mappings/v7/marc21records/drafts/marc21-v1.0.0.json
- invenio_records_marc21/records/mappings/v7/marc21records/marc21/marc21-v1.0.0.json
The change is necessary to get rid of following error message:
Text fields are not optimised for operations that require per-document field
data like aggregations and sorting, so these operations are disabled by default.
Please use a keyword field instead. Alternatively, set fielddata=true on
[created] in order to load field data by uninverting the inverted index. Note
that this can use significant memory.
This fix is a quick fix. it should be refactored to be a real mapping.
> fix: the missing mappings causes an error with the empty search feature

- .github/workflows/pypi-publish.yml
* it seams that also organizational secrets have to be given explicitly
to the called workflow
> fix: pypi-publish inherit secrets

- invenio_records_marc21/services/record/utils.py
* the used alias was only for published records, but the check should
also against drafts, otherwise it could happen that multiple drafts of
one import could exists which would then be handled by further
updates, which would lead to published duplicates because at that
stage no checks would be called.
> fix: wrong alias for drafts and records

- invenio_records_marc21/resources/serializers/serializer.py
- invenio_records_marc21/services/record/metadata.py
* the problem was, that the Marc21Metadata.emplace_datafield and
JsonToXmlVistor.visit_datafield methods didn't construct the Element in
the same way. One moved the tag attribute in the beginning the other in
the end of the datafield element. This leads to problems of checking the
equality in Marc21Metadata.exists method.
> fix: unify order of et.Element attributes

- invenio_records_marc21/services/components/metadata.py
- invenio_records_marc21/services/components/pids.py
- invenio_records_marc21/templates/invenio_records_marc21/deposit.html
**Bugfix**
loading the correct permissions in deposit app 
**Feature**
Adding the metadata to the new draft.
The caller is responsible for: moving the record data into the draft data. [Link](https://github.com/inveniosoftware/invenio-drafts-resources/blob/e803b70b5fda1f4eafc9bd89ef5eaed15ed74d48/invenio_drafts_resources/records/api.py#L180)
> Create new version

- invenio_records_marc21/services/record/metadata.py
* the problem was, that normally the subfield value is a list. the
reason behind this is, it is not guaranteed that a subfield
code is unique. But it also looks strange to use a list, if there is
only one element there (and it was used like that in
invenio-workflows-tugraz) therefore it is now possible to use a list
or a str
> fix: distinguish between str and list

- invenio_records_marc21/services/components/pids.py
* those two subfields are not needed so they are removed
> pids: remove 2 subfields

- .gitignore
- invenio_records_marc21/config.py
- invenio_records_marc21/resources/config.py
- invenio_records_marc21/resources/resources.py
- invenio_records_marc21/templates/invenio_records_marc21/user_dashboard/uploads.html
- invenio_records_marc21/ui/records/searchapp.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/Marc21RecordResultsListItem.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/user_dashboard/index.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/de/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/en/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/translations.pot
Update the layout for the user search an create an api endpoint to search for user records
**DEMO**
> Search: user dashboard

- invenio_records_marc21/ui/theme/__init__.py
`flask-menu`'s `MenuNode`s' visibility is configurable by passing `visible_when` on initialization.
`visible_when` has to be a `callable[[], bool]` for this to work, but was wrongly set to `True` up to now.
Also, up to now, visibility was to depend on authenticated-ness of the current user,
whereas it should depend on rights to view marc21 records.
These two issues are fixed with this PR.
NOTE: the corresponding html-template will also need to be updated for dashboard-visbility to work...
> fix: dashboard-visibility not working

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/landing_page/Marc21RecordManagement.js
- invenio_records_marc21/ui/theme/webpack.py
This pull request addresses the issue of an outdated dependency in the React application. The deprecated dependency has been removed and replaced with the latest version from rdm records module. This change ensures improved compatibility and functionality of the application.
- Removed the old dependency from the project configuration.
- Updated import statements to use the new source for the dependency.
- Ensured that all affected components and modules are properly updated to reflect the changes.
- Conducted comprehensive testing to ensure that the application functions as expected with the updated dependency.
- Verified that there are no regressions or compatibility issues introduced by the changes.
> Replace Deprecated Dependency in React App

- invenio_records_marc21/templates/invenio_records_marc21/user_dashboard/uploads.html
- invenio_records_marc21/translations/de/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
* it was not only the reason of the wording but also the problem with
the ordering of the translation imports. since the packages are used
after the my-site/translations the overrides there didn't worked
anymore. therefore the change here makes the override in
my-site/translations work again
> translations: update wording

- invenio_records_marc21/records/mappings/os-v2/marc21records/drafts/marc21-v2.0.0.json
- invenio_records_marc21/records/mappings/os-v2/marc21records/marc21/marc21-v2.0.0.json
This pull request introduces an optimization to our OpenSearch indexing process by ensuring that only static metadata fields are indexed. This change aims to improve search performance, reduce storage requirements, and streamline the indexing process by excluding dynamic fields that do not contribute to search relevancy.
Previously, our OpenSearch index included both static and dynamic metadata fields. Dynamic fields, while useful for data representation, do not play a significant role in search queries. Indexing these fields unnecessarily increases the index size and impacts search performance.
Modified the OpenSearch mapping configuration to set dynamic to false for the metadata object. This prevents automatic indexing of any new fields not explicitly defined in the mapping.
Recreate …
> Optimize OpenSearch Index by Indexing Only Static Metadata Fields

- invenio_records_marc21/config.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/facets.py
This pull request introduces functionality to allow users to filter records by resource type. This enhancement aims to improve the usability and efficiency of our search capabilities, enabling users to filter records more precisely based on the type of resource they are interested in.
The ability to filter by resource type has been a frequently requested feature from our user community. Previously, users could only filter records based on access type. This limitation made it challenging for users to narrow down search results to specific types of resources.
- Facet Update: The resource_type field is alredy indexed and searchable, allowing it to be used as a filter in search queries.
- Search API Enhancement: Modified the search API to accept resource_type as a facet parameter. Users can …
> Enable Resource Type facet in search

- invenio_records_marc21/config.py
- invenio_records_marc21/resources/config.py
follows an upstream-change from invenio-rdm-records: #1649
after the upstream change, upload-page API-calls accepts only vnd.inveniordm.v1+json as mime-type
but
our upload-page uses their javascript and hence now requires vnd.inveniordm.v1+json as mime-type
our backend does not provide that mime-type
this breaks a bunch of functionality of the upload-page, including file-upload
this PR fixes this by content-negotiating our custom mime-type (application/vnd.inveniomarc21.v1+marcxml)
> feat: files serializer use marc21 accept header

- invenio_records_marc21/resources/deserializers/schema.py
- invenio_records_marc21/resources/serializers/deposit/schema.py
- invenio_records_marc21/ui/theme/deposit.py
The metadata structure for deposit has changed, but the backend is still sending the previous format, which lacks the fields key. This causes serialization errors and results in empty records being saved, as the backend attempts to process incomplete metadata.
This fix updates the serializer to handle cases where the fields key is missing from the metadata. By marking fields as optional, the serializer can now handle responses from the backend that omit this key, preventing the creation and saving of empty records.
> fix(deposit): page render and save a empty record

- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/links.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/Marc21RecordResultsListItem.js
This pull request introduces the following enhancements and changes:
1. **Conditional Initialization of Record Links:**
- Added functionality to initialize record links conditionally within the service layer.
- The variable ```MARC21_RECORDS_SERVICE_LINKS``` is introduced to manage link configurations, ensuring flexibility and easier customization for other modules to load new links in the service.
2. **Integration with New Modules:**
- Extended support for new modules by enabling seamless initialization of links specific to their requirements.
- The implementation allows for scalability by ensuring that additional modules can define and override their link configurations.
> feat: Initialize Conditional Record Links in Service 

- invenio_records_marc21/records/jsonschemas/marc21/definitions-v1.0.0.json
* no idea why this has occurred now, maybe a newer version of jsonschema
package is more restricted on that behavior!
> fix: jsonschema user

- invenio_records_marc21/ui/records/__init__.py
The handler renders the permission denied template with a 403 status code when a user attempts to access a resource they don't have permission for.
-  added record_permission_denied_error function to errors.py
- the handler returns the  template with a 403 status code
- Anonymous user: for restricted files: wrong login prompt
- Authenticalted user: restricted files not checked
> feat: imp file access permissions for MARC21 records

- invenio_records_marc21/ui/records/records.py
* there where changes in app-rdm about the usage of record vs record_ui,
one is the serialized object the other not
> fix: record vs record_ui
