- invenio_records_marc21/services/__init__.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/services.py
moving service config class into a extra file
> move service config

- .github/workflows/tests.yml
- setup.py
Removing Python 3.7 support for marc21 records and update setup dependencies used versions and remove unnecessary modules
> Update Setup and CI

- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
adding translations to build a package for invenio-records-marc21
> modification: add translations

- .github/workflows/tests.yml
- invenio_records_marc21/cli.py
- invenio_records_marc21/records/__init__.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/records/models.py
- invenio_records_marc21/services/__init__.py
- invenio_records_marc21/services/components.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/permissions.py
- invenio_records_marc21/services/services.py
- tests/conftest.py
- tests/records/fields/conftest.py
- tests/records/fields/test_systemfield_files.py
- tests/services/test_record_service.py
Marc21 records add file service
> Service file

- invenio_records_marc21/records/mappings/v7/marc21records/drafts/marc21-v1.0.0.json
- invenio_records_marc21/records/mappings/v7/marc21records/marc21/marc21-v1.0.0.json
Removing old internal pid schema and add search keywords in metadata and add the parent schema to the elastic search mapping
> update ES7 mapping

- invenio_records_marc21/cli.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/records/jsonschemas/marc21/parent-v1.0.0.json
- invenio_records_marc21/records/systemfields/access/__init__.py
- invenio_records_marc21/records/systemfields/access/embargo.py
- invenio_records_marc21/records/systemfields/access/fields/__init__.py
- invenio_records_marc21/records/systemfields/access/fields/parent.py
- invenio_records_marc21/records/systemfields/access/fields/record.py
- invenio_records_marc21/records/systemfields/access/owners.py
- invenio_records_marc21/records/systemfields/access/protection.py
- invenio_records_marc21/records/systemfields/access/status.py
- invenio_records_marc21/services/components/__init__.py
- invenio_records_marc21/services/components/access.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/schemas/access/parent.py
- invenio_records_marc21/services/schemas/access/record.py
- invenio_records_marc21/services/services.py
- setup.py
- tests/conftest.py
- tests/records/fields/conftest.py
- tests/records/fields/test_systemfield_access.py
- tests/services/conftest.py
- tests/services/schemas/test_access.py
- tests/services/test_create_record.py
- tests/services/test_record_service.py
update access component of marc21 records
> Record access rights

- invenio_records_marc21/services/schemas/access/parent.py
- invenio_records_marc21/services/schemas/access/record.py
- tests/services/schemas/__init__.py
- tests/services/schemas/access/conftest.py
- tests/services/schemas/access/test_record.py
- tests/services/schemas/conftest.py
- tests/services/schemas/test_access.py
- tests/services/schemas/test_metadata.py
Remove embargo validation and add test-set for testing service marc21 schema
> AccessSchema update

- MANIFEST.in
- invenio_records_marc21/cli.py
- invenio_records_marc21/errors.py
- tests/conftest.py
- tests/test-metadata.xml
- tests/test-record.json
- tests/test_invenio_records_cli.py
Create a custom error message if in marc21 cli occurs an error. This PR closes the issue  #40
> Error message

- invenio_records_marc21/config.py
- invenio_records_marc21/ext.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/records/systemfields/__init__.py
- invenio_records_marc21/records/systemfields/access/fields/record.py
- invenio_records_marc21/records/systemfields/has_draft.py
- invenio_records_marc21/services/errors.py
- invenio_records_marc21/services/permissions.py
- invenio_records_marc21/services/services.py
- invenio_records_marc21/services/tasks.py
- setup.py
- tests/services/conftest.py
- tests/services/test_create_record.py
- tests/services/test_record_service.py
Lift an embargo in a record with a scheduled task
> Record embargo lift

- .github/workflows/tests.yml
Use as Database the PostgreSQL versions 12 and 13, for the CI tests.
> Update Github actions

- invenio_records_marc21/services/record/fields/data.py
- invenio_records_marc21/services/record/fields/leader.py
- invenio_records_marc21/services/record/metadata.py
Loading a metadata xml from etree to internal representation for the marc21 record service.
> Feature: load etree metadata

- invenio_records_marc21/cli.py
- invenio_records_marc21/data/example-templates.json
- invenio_records_marc21/ext.py
- invenio_records_marc21/system/__init__.py
- invenio_records_marc21/system/config.py
- invenio_records_marc21/system/models.py
- invenio_records_marc21/system/service.py
- setup.py
createing a template service allowing basic interation over the cli creating templates from a file and allow soft/hard delete of templates in db.
**DEMO**
Creating Templates in db:
`invenio marc21 templates create -f data/example-templats.json`
Soft delete template:
`invenio marc21 templates delete -n Test`
Hard delete template:
`invenio marc21 templates delete -n Test- f`
Hard delete all template:
`invenio marc21 templates delete --all - f`
> Template service

- INSTALL.rst
- README.rst
- docs/api.rst
- docs/conf.py
- docs/usage.rst
- invenio_records_marc21/__init__.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/services/services.py
- setup.py
Create a service documentation for Marc21 module and show how to install the module
> Service Documentation

- invenio_records_marc21/services/services.py
Access protection metadata  changed to record
> Bugfix: access protection

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21DepositForm.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21RecordSerializer.js
- invenio_records_marc21/ui/theme/webpack.py
add the access right field into the deposit app to modify record access status.
**Link:**
https://127.0.0.1:5000/marc21/uploads
> Deposit AccessRightField 

- invenio_records_marc21/config.py
- invenio_records_marc21/resources/serializers/fields/metadata.py
- invenio_records_marc21/resources/serializers/ui/serializers.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/templates/invenio_records_marc21/deposit.html
- invenio_records_marc21/templates/invenio_records_marc21/records/helpers/title.html
- invenio_records_marc21/ui/theme/__init__.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21Controller.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21RecordSerializer.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/fields/MetadataFields.js
- invenio_records_marc21/ui/theme/decorators.py
- invenio_records_marc21/ui/theme/deposit.py
- invenio_records_marc21/ui/theme/views.py
- tests/resources/serializers/conftest.py
- tests/resources/serializers/ui/fields/test_ui_metadata.py
- tests/resources/serializers/ui/test_serializers.py
Create new draft:
**Open Url:** _https://127.0.0.1:5000/marc21/uploads/<pid_value>_
**Publish the record**
> Deposit edit Marc21 records

- invenio_records_marc21/templates/invenio_records_marc21/records/helpers/details.html
- invenio_records_marc21/templates/invenio_records_marc21/records/helpers/title.html
- invenio_records_marc21/templates/invenio_records_marc21/records/macros/detail.html
- invenio_records_marc21/ui/records/__init__.py
- invenio_records_marc21/ui/records/filters.py
play safe, and show a value only if it is set
> bugfix: not present variable cause page rendering fault

- invenio_records_marc21/services/components/metadata.py
- invenio_records_marc21/services/schemas/metadata.py
- tests/conftest.py
- tests/records/systemfields/conftest.py
- tests/records/test_jsonschema.py
- tests/services/conftest.py
- tests/services/test_create_record.py
- tests/test-error-metadata.xml
- tests/test_invenio_records_cli.py
**SUMMARY**
If metadata validation error occur pass through the service to client.
**DEMO**
> Record service error handling 

- invenio_records_marc21/resources/resources.py
- invenio_records_marc21/resources/serializers/serializer.py
- invenio_records_marc21/resources/serializers/ui/serializers.py
- invenio_records_marc21/services/services.py
- tests/resources/serializers/conftest.py
- tests/resources/serializers/ui/test_serializers.py
Allow record deposit in backend and create a response according the frontend
**DEMO**
view `https://127.0.0.1:5001/marc21/uploads` and save a record
> Deposit records in backend 

- invenio_records_marc21/data/example-record.xml
- invenio_records_marc21/ext.py
- invenio_records_marc21/resources/serializers/datacite/schema.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/permissions.py
- setup.cfg
- tests/resources/serializers/conftest.py
- tests/resources/serializers/test_datacite_serializer.py
using the components from rdm records and celery task to register dois.
> Bugfix: Pids components from RDM

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/index.js
* it produces an error in the build process. error message
'SassError: expected "{".'
> fix: remove import of semantic css

- invenio_records_marc21/services/schemas/__init__.py
- invenio_records_marc21/services/schemas/metadata.py
- setup.cfg
The compiled jsonschema improve the metadata validation 1000 times.
> Improve the validation of Marc21 records

- invenio_records_marc21/__init__.py
- invenio_records_marc21/records/__init__.py
- invenio_records_marc21/services/__init__.py
- invenio_records_marc21/services/record/__init__.py
- invenio_records_marc21/services/record/metadata.py
- invenio_records_marc21/services/record/utils.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/index.js
- tests/services/record/test_marc21_metadata.py
- fix: remove import of semantic css
- improve: add subfs parameter to emplace_datafield
- api: add two functions moved from invenio-alma
- metadata: add default values to selector
- metadata: implement convert_json_to_marc21xml
- fix
> improvements

- invenio_records_marc21/services/services.py
updating  files only if no 'files' key is present in data and  override the correct parameter on update_draft
> Bugfix files in update_draft

- invenio_records_marc21/services/components/pids.py
- tests/services/test-metadata.json
- tests/services/test_pids_service.py
- tests/services/test_pids_tasks.py
- tests/services/test_record_service.py
Create the identifiers in the draft and publish in the other standard identifier field doi itentifier
> Identifier create in Draft

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21DepositForm.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/less/invenio_records_marc21/deposit.less
depends on : tu-graz-library/react-records-marc21#22
DEMO
=====
Metadata row
> Deposit UI

- invenio_records_marc21/__init__.py
- invenio_records_marc21/services/__init__.py
- invenio_records_marc21/services/record/__init__.py
- invenio_records_marc21/services/record/metadata.py
- invenio_records_marc21/services/record/types.py
- invenio_records_marc21/services/record/utils.py
- invenio_records_marc21/ui/theme/webpack.py
- tests/services/record/test_marc21_metadata.py
- services: add types
- services: add exception for common search
- ui: update react-records-marc21
- metadata: add exists method
- bugfix: files enabled
- modification: create identifier with draft
- modification: put doi into the metadata
- tests: testset update
- metadata: add param do_publish
- modification: add multiple files to record
- global: pass through exports
- fixes:
> add theses workflow

- invenio_records_marc21/records/api.py
- invenio_records_marc21/records/systemfields/__init__.py
- invenio_records_marc21/records/systemfields/status.py
- invenio_records_marc21/services/schemas/__init__.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21DepositForm.js
- invenio_records_marc21/ui/theme/deposit.py
Show the status of a record on top of the  AccessRightField.
> Display Record status

- invenio_records_marc21/config.py
- invenio_records_marc21/templates/invenio_records_marc21/uploads.html
- invenio_records_marc21/ui/theme/__init__.py
- invenio_records_marc21/ui/theme/views.py
Add a dashboard entry for marc21 records to user dashboard
**DEMO**
> Create dashboard entry for marc21

- invenio_records_marc21/__init__.py
- invenio_records_marc21/cli.py
- invenio_records_marc21/config.py
- invenio_records_marc21/errors.py
- invenio_records_marc21/ext.py
- invenio_records_marc21/services/generators.py
- invenio_records_marc21/services/permissions.py
- setup.cfg
- tests/conftest.py
- tests/services/conftest.py
Allow only users with a tugraz manager need to create and update records
> Record manager permissions

- .gitignore
- MANIFEST.in
- babel.ini
- invenio_records_marc21/templates/invenio_records_marc21/uploads.html
- invenio_records_marc21/translations/de/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/components/EditButton.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/deposit/Marc21DepositForm.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/landing_page/Marc21RecordManagement.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/landing_page/Marc21RecordVersionsList.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/i18next-scanner.config.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/i18next.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/de/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/en/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/index.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/package-lock.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/package.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/scripts/compileCatalog.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/scripts/initCatalog.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/translations.pot
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/package-lock.json
- invenio_records_marc21/ui/theme/webpack.py
Update german translations and add frontend translations
> Translations

- invenio_records_marc21/services/permissions.py
changing the permissions to search public records without a login
> Bugfix: Search record permissions

- invenio_records_marc21/services/permissions.py
adding permission to fetch file content form server
> Previewer allow to access file content

- invenio_records_marc21/services/components/pids.py
- tests/conftest.py
- tests/services/test-metadata.json
- tests/services/test_record_service.py
* the 856 field is necessary for the marc21 standard
> metadata: add 856 field after doi creation

- invenio_records_marc21/services/record/metadata.py
* within alma the ind1 and ind2 are set to space
> fix: metadata export needs a space

- invenio_records_marc21/services/components/pids.py
- invenio_records_marc21/services/record/metadata.py
* the change was requested. characters should be first and numbers
afterwards.
> metadata: subfs, character before numbers

- invenio_records_marc21/templates/invenio_records_marc21/uploads.html
* the fix incorporates also a refactoring of the html structure, which
revelead a missing close div tag tag.
> fix: remove whitespace and close div tag

- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/details.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/record.html
Import tamplates with correct path
> Bugfix: import landing page

- invenio_records_marc21/config.py
- invenio_records_marc21/resources/serializers/ui/fields/metadata.py
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/details/subjects.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/export.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/authors.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/description.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/details.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/export.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/footer.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/side_bar.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/subjects.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/title.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/macros/detail.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/macros/doi.html
- invenio_records_marc21/templates/invenio_records_marc21/landing_page/record.html
- invenio_records_marc21/translations/de/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
- invenio_records_marc21/ui/records/records.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/landing_page/index.js
- landing_page: use improved export
- landing-page: change created at to published
- landing_page: increase space above title
- refactoring: variable naming
> fix landing page

- invenio_records_marc21/config.py
- invenio_records_marc21/resources/serializers/serializer.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/facets.py
- invenio_records_marc21/services/pids/datacite.py
- invenio_records_marc21/templates/invenio_records_marc21/search/search.html
- invenio_records_marc21/templates/invenio_records_marc21/user_dashboard/uploads.html
- invenio_records_marc21/translations/de/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
- invenio_records_marc21/ui/records/__init__.py
- invenio_records_marc21/ui/records/searchapp.py
- invenio_records_marc21/ui/theme/__init__.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/Marc21RecordResultsGridItem.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/Marc21RecordResultsListItem.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/index.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/user_dashboard/index.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/de/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/en/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/translations.pot
- invenio_records_marc21/ui/theme/webpack.py
**DEMO**
Marc21 search page: 
Marc21 user upload page:
> Search application

- invenio_records_marc21/records/fields/resourcetype.py
- invenio_records_marc21/resources/serializers/ui/fields/metadata.py
- invenio_records_marc21/translations/de/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
> Metadata resource type

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/index.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/user_dashboard/index.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/de/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/messages/en/translations.json
- invenio_records_marc21/ui/theme/assets/semantic-ui/translations/invenio_records_marc21/translations.pot
changing the empty result component in search and user_dashboard
> Empty search result

- invenio_records_marc21/config.py
- invenio_records_marc21/translations/de/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/en/LC_MESSAGES/messages.po
- invenio_records_marc21/translations/messages.pot
enable translations in configuration
> Translations in config module

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/Marc21RecordResultsListItem.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/user_dashboard/index.js
add the view and result button only on user dashboard and not on the search page
> Result item on dashboard

- invenio_records_marc21/records/api.py
Add the schema name to the record and draft to save it in the metadata. This is intended for future differentiation between versions.
> Bugfix: add schema to record

- invenio_records_marc21/services/config.py
* otherwise the queue of rdm records was used
> fix: indexer needs queue name

- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/index.js
Description:
=======================
This pull request introduces a feature to enhance the style consistency of the publication search bar by utilizing the `RDMRecordMultipleSearchBarElement` component.
Changes Made:
------------------------
- Implemented the `RDMRecordMultipleSearchBarElement` component for the publication search bar.
- Ensured that the style of the publication search bar matches the overall design aesthetic of the application.
These changes aim to create a cohesive user experience by maintaining a consistent visual style across different elements of the application.
Demo
-------
> Apply Same Style to Publication Search Bar

- invenio_records_marc21/resources/serializers/ui/serializers.py
* until now the embargo date shown on the landing page was extracted
from access.embargo.until. this value is now overwritten by the value
of the marc21 metadata field 971.1..c
> landingpage: embargo date from marc21 metadata

- invenio_records_marc21/config.py
Description:
----------------
This pull request re-enables the functionality to export records in a user-friendly format. Previously implemented but temporarily disabled, this feature allows users to export records in a visually appealing and easy-to-read format. By re-enabling this functionality, users can once again benefit from the enhanced readability and comprehension provided by the user-friendly export format.
> Export Records in User-Friendly Format

- invenio_records_marc21/services/permissions.py
This pull request introduces modifications to the permission settings that govern record access management. The changes aim to refine how access is granted and managed, ensuring more granular and secure control over records.
- **Refined Permission Logic**: Updated the logic that defines for managing record access from `manager` to `curator`.
> modification: Enhance record access management

- invenio_records_marc21/config.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/resources/serializers/ui/schema.py
- invenio_records_marc21/services/config.py
- invenio_records_marc21/services/facets.py
- invenio_records_marc21/ui/records/searchapp.py
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/search/components/Marc21RecordResultsListItem.js
- invenio_records_marc21/ui/theme/assets/semantic-ui/js/invenio_records_marc21/user_dashboard/index.js
- tests/records/systemfields/test_systemfield_files.py
search published and not published records in user dashboard and add is_published in index
> bugfix: search records user dashboard

- invenio_records_marc21/templates/invenio_records_marc21/user_dashboard/uploads.html
This pull request activates the dashboard menu item to improve user navigation and accessibility within the application.
> Activate Dashboard Menu Item

- invenio_records_marc21/resources/deserializers/schema.py
- invenio_records_marc21/resources/serializers/deposit/schema.py
- invenio_records_marc21/services/components/pids.py
- refactor: make the code simpler
- fix: fields could be missing
> fix doi 856

- invenio_records_marc21/__init__.py
- invenio_records_marc21/records/api.py
- invenio_records_marc21/services/__init__.py
- invenio_records_marc21/services/links.py
- invenio_records_marc21/services/record/__init__.py
- invenio_records_marc21/services/record/metadata.py
- setup.cfg
- tests/conftest.py
- metadata: add new method
- rdm: compatibility
- tests: make redis host:port configurable
> fix landing page title

- invenio_records_marc21/config.py
- invenio_records_marc21/ext.py
- invenio_records_marc21/resources/deserializers/schema.py
- fix(deserializer): AVE is allowed
- refactor(config): config variables init
> fix keys not around

- invenio_records_marc21/services/generators.py
* Marc21Manager should see all search results in dashboard
> fix: manager should see results

- invenio_records_marc21/templates/invenio_records_marc21/landing_page/helpers/details.html
* there are some implemenation details for showing the correct marc21
datafield which are wrong, this has to be done better
> revert: some details are wrong
